In [1]:
pip install pandasql

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from pandasql) (1.21.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from pandasql) (1.3.5)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.7/dist-packages (from pandasql) (1.4.37)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pandasql) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->pandasql) (1.15.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from sqlalchemy->pandasql) (1.1.2)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from sqlalchemy->pandasql) (4.11.4)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy->pandasql) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy->pandasql) (3.8.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26784 sha256=272fa2afeda62b13b2c59527370bf42273cc4065e99ca12144f29cae92da6e79
  Stored in directory: /root/.cache/pip/wheels/5c/4b/ec/41f4e116c8053c3654e2c2a47c62b4fca34cc67ef7b55deb7f
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [2]:
import pandas as pd
import pandasql as ps

In [6]:
from google.colab import files
uploded = files.upload()

Saving insurance_data.csv to insurance_data.csv

In [ ]:
insurance_data = pd.read_csv('insurance_data.csv')
insurance_data

In [ ]:
employee_data = pd.read_csv('employee_data.csv')
employee_data

In [13]:
Task7 = ps.sqldf("""
---------------------WRITE QUERY BELOW---------------------

SELECT 
       COUNT(DISTINCT INSURANCE_TYPE) AS TYPES_OF_POLICY, E.AGENT_NAME, SUM(CLAIM_AMOUNT) AS TOTAL_CLAIM_AMOUNT
FROM 
       insurance_data I JOIN employee_data E ON I.AGENT_ID = E.AGENT_ID
GROUP BY 
       E.AGENT_NAME
HAVING 
       COUNT(INSURANCE_TYPE) > 2
ORDER BY 
       TOTAL_CLAIM_AMOUNT DESC;       
           
   

---------------------WRITE QUERY ABOVE---------------------
""")

Task7

      TYPES_OF_POLICY        AGENT_NAME  TOTAL_CLAIM_AMOUNT
0                   6       Don Filkins              528800
1                   4     Clara Barnett              489000
2                   5       Roger Burns              422100
3                   6       Robert Ward              417100
4                   4  Salvador Soriano              400400
...               ...               ...                 ...
1184                3      Laura Staggs               10800
1185                2     Martin Murphy                9000
1186                2       Larry Dryer                7400
1187                2     Mary Franklin                5600
1188                3    Thelma Salinas                5500

[1189 rows x 3 columns]